DROP TABLE IF EXISTS women;

CREATE TABLE women(id INTEGER PRIMARY KEY, lname VARCHAR(50), fname VARCHAR(50),
mname VARCHAR(50), yob INTEGER, gender CHAR(1), wage DECIMAL,
husband INTEGER UNIQUE, children_count INTEGER);
